server:
  port: 8080  # Порт, на котором будет работать Spring Boot приложение

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss  # Формат даты для JSON
    time-zone: UTC  # Часовой пояс UTC
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb  # URL основной БД
    username: postgres  # Пользователь основной БД
    password: postgres  # Пароль основной БД
    driver-class-name: org.postgresql.Driver  # Драйвер PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update  # Режим работы Hibernate (валидация схемы)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Диалект PostgreSQL
        format_sql: true  # SQL в логах
    show-sql: true  # Показывать SQL в логах
